#!/bin/bash

if [ $# != 2 ]
then
    echo "usage: $0 <executable> <output>"
    echo "    bundle executable and libraries in a self-executing archive, by <benoit.favre@lif.univ-mrs.fr> 2013-06-27"
    exit 1
fi

if [ `file -b "$1" | cut -f1 -d" "` != 'ELF' ]; then
    echo "error: \"$1\" is not an executable"
    exit 1
fi

target=`mktemp -d`
binary=`basename $1`
output=$2

set -o errexit -o pipefail

# generate directory with all libraries + loader
cp $1 "$target/$binary"
cp `ldd "$1" | grep ld-linux | awk '{print $1}'` "$target/ld-linux"
mkdir "$target/lib"
ldd "$1" | awk 'NF == 4 {print $3}' | xargs cp -t "$target/lib"

# generate script to uncompress and exectute binary
(
cat <<EOF
#!/bin/bash
set -o errexit -o pipefail
target=\`mktemp -d\`
trap "rm -rf \$target" SIGINT SIGTERM
tail -n +11 "\$0" | tar -C \$target -xf -
set +o errexit +o pipefail
"\$target/ld-linux" --library-path "\$target/lib" "\$target/$binary" \$@
value=\$?
rm -rf "\$target"
exit \$value
EOF
tar -C "$target" -cf - ld-linux "$binary" lib
) > "$output"

rm -rf "$target"
chmod +x "$output"
